baseURL = "https://stklauz.github.io/"
languageCode = "en-us"
title = "cláudia carvalho"
sectionPagesMenu = "main"
summaryLength = 20
enableRobotsTXT = true


# Theme Settings
theme = "lemon"
[params]
  author = "Cláudia Carvalho" # Add the name of the author (this theme only supports one author)
  description = "My name is Cláudia, but most people call me Klauz. I’m a Product Designer based in Portugal."
  keywords = "UX Designer, design, product management, blog, Cláudia Carvalho, stklauz"
  linkedin = "https://www.linkedin.com/in/claudiacvlho"
[author]
  name = "Cláudia Carvalho" # Used by the foot copyright
[menu]
  [[menu.main]]
    identifier = "blog"
    name = "Blog"
    url = "/blog/"
    weight = 1
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 2
 
 

