baseURL = "https://stklauz.github.io/"
languageCode = "en-us"
title = "making things"
sectionPagesMenu = "main"
summaryLength = 20


# Theme Settings
theme = "lemon"
[params]
  author = "Klauz" # Add the name of the author (this theme only supports one author)
  description = "Cláudia Carvalho is a UX Designer interested in Product and Productivity, writing a blog about making things"
[author]
  name = "Cláudia Carvalho" # Used by the foot copyright
[menu]
  [[menu.main]]
    identifier = "life"
    name = "Life"
    url = "/categories/Life/"
    weight= 1
  [[menu.main]]
    identifier = "product"
    name = "Product"
    url = "/categories/product/"
    weight= -1
 

