baseURL = "https://stklauz.github.io/"
languageCode = "en-us"
title = "making things"
sectionPagesMenu = "main"
summaryLength = 20


# Theme Settings
theme = "lemon"
[params]
  author = "Cláudia Carvalho" # Add the name of the author (this theme only supports one author)
  description = "My name is Cláudia, but most people call me Klauz. I’m a Product Designer based in Portugal, learning how to make things that add value to people’s lives."
  keywords = "UX Designer, design, product management, blog, Cláudia Carvalho, stklauz"
[author]
  name = "Cláudia Carvalho" # Used by the foot copyright
[menu]
  [[menu.main]]
    identifier = "others"
    name = "Others"
    url = "/categories/others/"
    weight= 1
  [[menu.main]]
    identifier = "design"
    name = "Design"
    url = "/categories/design/"
    weight= 1
  [[menu.main]]
    identifier = "product"
    name = "Product"
    url = "/categories/product/"
    weight= -1
 
 

