baseURL = "https://stklauz.github.io/"
languageCode = "en-us"
title = "making things"
sectionPagesMenu = "main"
summaryLength = 20


# Theme Settings
theme = "tale"
[params]
  author = "Klauz" # Add the name of the author (this theme only supports one author)
  description = "Cláudia Carvalho's blog about making things"
[author]
  name = "Cláudia Carvalho" # Used by the foot copyright
[menu]
